services:
  - type: web
    name: vitibrasil-api
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.core.app:app --host 0.0.0.0 --port 10000
